### ISSUE TITLE
knapsack_dp_dominance中如何进行回溯打印方案呢？

### ISSUE THREAD

**Issue by ArchFeh** [jameslao/Algorithmic-Pearls#1]
有幸阅读到了大佬的文章，受益匪浅。但是在[knapsack_dp_dominance](https://github.com/jameslao/Algorithmic-Pearls/blob/master/0-1-Knapsack/knapsack_dp_dominance.py)中因为采用了不一样的merge方法，所以不知道该如何回溯了，希望指点迷津

**Comment by jameslao** [comment]
确实比较难直接回溯，要拿到方案的话得额外保存每个节点的方案

**Comment by ArchFeh** [comment]
不知道用什么比较好的方式保存每个节点的方案

**Comment by jameslao** [comment]
比如直接在`B`里面保存`i`

```
    A = deque([(0, 0, [])])
....
            B.append((item[0] + vw[i][0], item[1] + vw[i][1], item[2] + [i]))
```

最后直接输出`A[-1]`

**Comment by ArchFeh** [comment]
明白了！茅塞顿开！
